lib: implement new RPC function
oktetlabs/test-environment pull request #29
Opened 2023-11-28 20:52 UTC by okt-borissh

Implement the function rpc_epoll_pwait2_alt(), which is similar to
rpc_epoll_pwait(), except that the argument timeout is of type
struct tarpc_timespec *.

The function epoll_pwait2_alt() is used in order to allow building TE
on systems where epoll_pwait2() is not defined.

Signed-off-by: Boris Shleyfman <bshleyfman@oktet.co.il>
Reviewed-by: Yurij Plotnikov <yurij.plotnikov@arknetworks.am>

2023-11-28 21:02 UTC, ol-arteman requested changes
The commit subject line should be more specific (and the component name is wrong, it should be `lib/rpcxdr`, by convention). And the rest of commit description should be less specific, focusing on why the function is needed.

2023-11-29 00:37 UTC, ol-arteman requested changes

2023-12-08 16:51 UTC, ol-andrewr commented
Summary of the changeset is too generic

2024-05-28 11:16 UTC, ol-arteman approved these changes

2024-05-28 12:38 UTC, closed without merging

2024-05-28 12:39 UTC, ol-arteman commented
Scheduled for the next release.