agents/unix: add config nodes for amount of memory
oktetlabs/test-environment pull request #4
Opened 2022-11-02 15:45 UTC by okt-yurijp

Add /agent/hardware/node/memory and /agent/hardware/node/memory/free to configuration tree and add implementation of calculation of such values.

Signed-off-by: Boris Shleyfman <bshleyfman@oktet.co.il>
Reviewed-by: Yurij Plotnikov <yurij.plotnikov@arknetworks.am>

2022-11-02 15:56 UTC, ol-arteman requested changes

2022-11-02 16:14 UTC, ol-arteman reviewed
Also, I should note that new nodes in the Configurator tree should generally be accompanied by a TAPI wrapper. This may be a separate commit, though, and a separate pull request, i.e. it's not a hard requirement, but it's very desired.

2022-11-07 08:08 UTC, ol-arteman requested changes

2022-11-07 08:08 UTC, ol-arteman commented on agents/unix/conf/base/conf_cpu.c
> +  long int n_pages, page_size;
Just `long`

2022-11-07 08:08 UTC, ol-arteman commented on agents/unix/conf/base/conf_cpu.c
> +  n_pages = sysconf(_SC_PHYS_PAGES);
`_SC_PHYS_PAGES` is not in POSIX, so it's needed to check for its presence with `#ifdef _SC_PHYS_PAGES` (and, I believe, just return `0` if it is not present)

2022-11-07 08:08 UTC, ol-arteman commented on agents/unix/conf/base/conf_cpu.c
> +  long int avail_pages, page_size;
Just `long`

2022-11-07 08:08 UTC, ol-arteman commented on agents/unix/conf/base/conf_cpu.c
> +  avail_pages = sysconf(_SC_AVPHYS_PAGES);
Same here as with `_SC_PHYS_PAGES`

2022-11-08 13:32 UTC, ol-arteman commented on agents/unix/conf/base/conf_cpu.c
> +  return 0;
This might produce a warning on unused `page_size` and a warning about dead code that follows.

2022-11-11 16:30 UTC, ol-arteman requested changes

2022-11-11 16:30 UTC, ol-arteman commented on agents/unix/conf/base/conf_cpu.c
> +}
I'd say it should be like this:
```
uint64_t mem = 0;
#ifdef _SC_PHYS_PAGES
....
#endif
snprintf(value, RCF_MAX_VAL, "%" PRIu64, mem);
return 0;
```

That way we're totally sure that the node returns a valid number, but if it cannot be detected - it's just `0`

2022-11-14 10:52 UTC, ol-arteman approved these changes

2022-11-14 14:03 UTC, okt-yurijp commented
Excuse me, but is there any chance to see this patch in Test Environment in nearest future? We have one more patch on tapi functions for memory and available memory, but I think that it's not worth to make pull request for it, before the code from this PR will be pushed, because if tapi functions code will be pushed before this one, then build will be broken.

2022-11-14 14:36 UTC, ol-arteman commented
@ol-andrewr it's up to you to merge, I am totally ok with the patch.

2022-11-14 15:16 UTC, closed without merging

2022-11-14 15:21 UTC, ol-andrewr commented
will be a part of the next snapshot