lib/tapi_gtest: improve job options handling
oktetlabs/test-environment pull request #40
Opened 2024-06-12 17:25 UTC by okt-yurijp

Update tapi_gtest_init() function and tapi_gtest structure to handle more options for Gtest.

Signed-off-by: Yurij Plotnikov <yurij.plotnikov@arknetworks.am>
Reviewed-by: Konstantin Ushakov <kushakov@oktet.co.il>
Reviewed-by: Denis Pryazhennikov <denis.pryazhennikov@arknetworks.am>

2024-11-02 10:02 UTC, ol-andrewr commented
@okt-yurijp Could you rebase the PR, please.

2024-11-02 18:33 UTC, ol-andrewr approved these changes

2024-11-08 18:08 UTC, ol-arteman requested changes

2024-11-08 18:08 UTC, ol-arteman commented on lib/tapi_gtest/tapi_gtest.c
> +    if ((rc = te_string_append(&buf, "%s.%s", gtest->group, gtest->name)) != 0)
This check is not needed anymore, as `te_string_append` always returns `0`.

2024-11-08 18:08 UTC, ol-arteman commented on lib/tapi_gtest/tapi_gtest.c
>          return rc;
But now there is a memory leak if `gtest_build_argv` returns non-zero, the memory for `buf.ptr` is never freed.

2024-12-02 15:52 UTC, closed without merging