agents/unix: allow netconsole over routed networks
oktetlabs/test-environment pull request #42
Opened 2024-08-28 11:22 UTC by okt-galaktionov

If the route to the target involves a gateway, use the gateway's MAC address as destination MAC.

Testing done: this patch fixed netconsole for agents running in containerized VMs

2024-08-28 13:17 UTC, ol-alexandra requested changes
I think that in many cases there is no need to resolve this ARP; the ARP is already here.  I propose to try to get the ARP info immediately and send a UDP datagram only if needed.

2024-09-04 09:02 UTC, ol-alexandra approved these changes
Ack

2024-09-04 10:09 UTC, ol-arteman commented on agents/unix/conf/base/conf_netconsole.c
> +    rc = sendto(s, "", strlen("") + 1, 0,
`sendto()` returns `ssize_t` and `rc` has type `int`.

2024-09-04 10:11 UTC, ol-arteman commented on agents/unix/conf/base/conf_netconsole.c
> +    int           tmp_err;
I'd say `te_errno rc;` and instead of `tmp_err = errno; ... return te_rc_os2te(tmp_err)` use `rc = TE_OS_RC(TE_TA_UNIX, errno); ... return rc;`

2024-09-04 10:14 UTC, ol-arteman commented on agents/unix/conf/base/conf_netconsole.c
> +             0xff & (int)(remote_hwaddr.sa_data[5]));
As you're touching it anyway: we have `TE_PRINTF_MAC_FMT` and `TE_PRINTF_MAC_VAL`

2024-11-02 09:49 UTC, ol-andrewr requested changes

2024-11-02 09:49 UTC, ol-andrewr commented on agents/unix/conf/base/conf_netconsole.c
> +                  (struct sockaddr *)remote_ip,
SA(remove_ip) (see te_defs.h)

2024-11-02 09:49 UTC, ol-andrewr commented on agents/unix/conf/base/conf_netconsole.c
> +    ret = bind(s, (struct sockaddr *)local_ip, sizeof(*local_ip));
SA(local_ip) see te_defs.h

2024-11-02 09:49 UTC, ol-andrewr commented on agents/unix/conf/base/conf_netconsole.c
> +    ((struct sockaddr_in *)&remote_hwaddr_req.arp_pa)->sin_port = 0;
SIN(&remove_hwaddr_req.arp_pa)

2024-11-02 09:49 UTC, ol-andrewr commented on agents/unix/conf/base/conf_netconsole.c
> +    ((struct sockaddr_in *)&remote_hwaddr_req.arp_ha)->sin_family =
SIN(&remove_hwaddr_req.arp_ha)

2024-11-02 09:49 UTC, ol-andrewr commented on agents/unix/conf/base/conf_netconsole.c
> +
the function should either use sockaddr_in or the sa_family here and return error if it is not IPv4

2024-11-05 07:44 UTC, ol-andrewr requested changes

2024-11-05 07:44 UTC, ol-andrewr commented on agents/unix/conf/base/conf_netconsole.c
> +    (SIN(&remote_hwaddr_req.arp_pa))->sin_port = 0;
extra parenthesis are not required

2024-11-05 07:44 UTC, ol-andrewr commented on agents/unix/conf/base/conf_netconsole.c
> +    (SIN(&remote_hwaddr_req.arp_ha))->sin_family =
extra parenthesis are not required

2024-11-05 07:44 UTC, ol-andrewr commented on agents/unix/conf/base/conf_netconsole.c
> +                                                            ARPHRD_ETHER;
strange alignment

2024-11-05 07:44 UTC, ol-andrewr commented on agents/unix/conf/base/conf_netconsole.c
> +        rc = get_remote_mac(SIN(&local_ipv4_addr), ifname, SIN(&gateway_ipv4_addr),
local_ipv4_addr and gateway_ipv4_addr are a sockaddr_in, so SIN is not required

2024-11-05 07:44 UTC, ol-andrewr commented on agents/unix/conf/base/conf_netconsole.c
> +        rc = get_remote_mac(SIN(&local_ipv4_addr), ifname, SIN(&remote_ipv4_addr),
local_ipv4_addr and gateway_ipv4_addr are a sockaddr_in, so SIN is not required

2024-11-06 06:25 UTC, ol-andrewr approved these changes

2024-11-06 06:26 UTC, ol-andrewr commented on agents/unix/conf/base/conf_netconsole.c
> +    usleep(500000);
Since nobody suggested better solution we should move forward. May be we'll find out how to improve it in the future.

2024-11-06 07:08 UTC, ol-arteman commented on agents/unix/conf/base/conf_netconsole.c
> +    usleep(500000);
Ok, at least:
- let's replace the deprecated `usleep()` with `nanosleep()`
- and let's have a timeout as named constant

2024-11-07 09:51 UTC, ol-andrewr approved these changes

2024-11-07 09:51 UTC, ol-andrewr commented on agents/unix/conf/base/conf_netconsole.c
> +        .tv_nsec = 500000000,
TE_MS2NS(500)

2024-12-02 15:12 UTC, ol-arteman approved these changes

2024-12-02 15:37 UTC, closed without merging