Various RGT fixes
oktetlabs/test-environment pull request #43
Opened 2024-08-28 11:24 UTC by okt-galaktionov

A series of minor fixes in RGT focused mostly on memory safety.

Testing done: this patch fixed RGT segfaults on Ubuntu 22.04

2024-10-10 06:41 UTC, ol-andrewr requested changes

2024-10-10 06:41 UTC, ol-andrewr commented on tools/rgt/rgt-format/xml2html-multi/xml2html-multi.c
> +                             multi_opts.shared_url ? multi_opts.shared_url : "");
please, compare vs NULL explicitly

2024-10-10 06:41 UTC, ol-andrewr commented on tools/rgt/rgt-format/xml2html-multi/xml2html-multi.c
> +                             multi_opts.docs_url ? multi_opts.docs_url : "");
please, compare vs NULL explicitly

2024-10-16 13:11 UTC, ol-andrewr commented on tools/rgt/lib/tmpls/rgt_tmpls_lib.h
> +                                     __attribute__((format(printf, 3, 4)));
TE_LIKE_PRINTF should be used

2024-10-17 07:30 UTC, ol-andrewr approved these changes

2024-10-18 09:21 UTC, ol-arteman approved these changes

2024-10-18 09:21 UTC, closed without merging