lib/tapi_rpc: add readlink support
oktetlabs/test-environment pull request #6
Opened 2022-12-07 09:11 UTC by okt-galaktionov

This function is required to determine, for example, a network interface's BDF given its name.
To do that, a symlink in sysfs has to be read.

Tested with a pending patch to net-drv-ts. This functionality is required there to determine the debug paths in sysfs.

2022-12-07 15:51 UTC, ol-arteman reviewed
By convention, the component name should be `lib/rpcxdr`. Also, the commit description should have `Signed-off-by: Yurij Plotnikov <yurij.plotnikov@arknetworks.am>` as the formal author of the patch.

2022-12-07 15:56 UTC, ol-arteman requested changes

2022-12-07 15:56 UTC, ol-arteman commented on lib/rpcxdr/tarpc_base.x.m4
> +    char                resolved_path<>;
it should be `string<>`, not `char<>`, these are pretty different things in XDR, and while the latter is used extensively throughout legacy code, it's still an error.

2022-12-07 15:56 UTC, ol-arteman commented on lib/tapi_rpc/tapi_rpc_unistd.h
> + * @param rpcs      RPC server handle
Either dots at the end or lower case letters at the start.

2022-12-07 15:56 UTC, ol-arteman commented on lib/rpcserver/tarpc_imp.c
> +    buf = (char *)calloc(sizeof(in->bufsize), 1);
`TE_ALLOC`, please. And the result of memory allocation shall never be explicitly cast to a specific type.

2022-12-07 15:56 UTC, ol-arteman commented on lib/rpcserver/tarpc_imp.c
> +        out->common._errno = TE_RC(TE_TA_UNIX, TE_ENOMEM);
`TE_FATAL_ERROR`

2022-12-08 13:40 UTC, ol-arteman approved these changes
The patch itself is ok, however, we need to decide whether additional `Signed-off-by: Yurij Plotnikov <yurij.plotnikov@arknetworks.am>` is needed or not. Also PR should include testing done info.

2022-12-08 13:53 UTC, okt-galaktionov commented
Yurij only reviewed the patch, he didn't write any part of it. I don't think he needs to sign it off.

As for testing done, I'm not sure there's anything else I can add to what the PR already says.
This patch was used to successfully fix the `basic/read_sysfs` test in [net-drv-ts](https://github.com/Xilinx-CNS/cns-net-drv-ts). The fix is
not in that repo yet. If you need any details, please tell me.

2022-12-08 13:57 UTC, ol-arteman commented
> Yurij only reviewed the patch, he didn't write any part of it. I don't think he needs to sign it off.

I know. But I suppose @ol-andrewr thinks otherwise. At least, in the previous case he insisted on having `Signed-off-by` by the formal commit author. 

> 
> As for testing done, I'm not sure there's anything else I can add to what the PR already says. This patch was used to successfully fix the `basic/read_sysfs` test in [net-drv-ts](https://github.com/Xilinx-CNS/cns-net-drv-ts). The fix is not in that repo yet. If you need any details, please tell me.

Ok, I am satisfied.

2022-12-08 14:05 UTC, okt-galaktionov commented
I don't understand what you mean by "formal commit author". Could you elaborate?

2022-12-08 14:30 UTC, ol-arteman commented
> I don't understand what you mean by "formal commit author". Could you elaborate?
Ah, sorry. You are making this PR on your own behalf and you are the formal author, not Yurij. Case dismissed.

2022-12-20 00:14 UTC, closed without merging